import type { Task, TeamMember } from './types';

export const SEED_MEMBERS: TeamMember[] = [
  { id: 'm1', name: '김지훈', initials: '김지', color: 'bg-blue-500' },
  { id: 'm2', name: '이수연', initials: '이수', color: 'bg-purple-500' },
  { id: 'm3', name: '박민준', initials: '박민', color: 'bg-amber-500' },
  { id: 'm4', name: '최아영', initials: '최아', color: 'bg-rose-500' },
  { id: 'm5', name: '정현우', initials: '정현', color: 'bg-teal-500' },
];

const now = new Date();
const days = (n: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() + n);
  return d.toISOString().split('T')[0];
};
const past = (n: number) => days(-n);

export const SEED_TASKS: Task[] = [
  {
    id: 't1',
    title: '메인 대시보드 UI 개선',
    description: '사용자 피드백을 반영하여 대시보드 레이아웃과 차트 컴포넌트를 개선합니다. 반응형 레이아웃 적용 및 다크모드 지원 포함.',
    status: 'in_progress',
    priority: 'high',
    category: 'feature',
    assigneeId: 'm1',
    dueDate: days(3),
    tags: ['UI', '대시보드', '반응형'],
    createdAt: past(5),
    updatedAt: past(1),
  },
  {
    id: 't2',
    title: '로그인 페이지 버그 수정',
    description: 'Safari에서 소셜 로그인 버튼이 클릭되지 않는 문제 수정. iOS 17 이상에서도 동일하게 발생.',
    status: 'todo',
    priority: 'urgent',
    category: 'bug',
    assigneeId: 'm2',
    dueDate: days(1),
    tags: ['버그', 'Safari', '로그인'],
    createdAt: past(2),
    updatedAt: past(2),
  },
  {
    id: 't3',
    title: 'API 문서화 작업',
    description: 'REST API 엔드포인트 전체에 대한 Swagger 문서 작성. 요청/응답 예시 및 에러 코드 포함.',
    status: 'review',
    priority: 'medium',
    category: 'docs',
    assigneeId: 'm5',
    dueDate: days(7),
    tags: ['API', 'Swagger', '문서화'],
    createdAt: past(8),
    updatedAt: past(1),
  },
  {
    id: 't4',
    title: '결제 플로우 리디자인',
    description: '전환율 향상을 위한 결제 단계 간소화. A/B 테스트 결과 기반으로 3단계 → 2단계로 축소.',
    status: 'done',
    priority: 'high',
    category: 'design',
    assigneeId: 'm3',
    dueDate: past(2),
    tags: ['결제', 'UX', 'A/B테스트'],
    createdAt: past(14),
    updatedAt: past(2),
  },
  {
    id: 't5',
    title: 'CI/CD 파이프라인 최적화',
    description: '빌드 시간을 현재 8분에서 3분 이내로 단축. Docker 레이어 캐싱 및 병렬 테스트 실행 적용.',
    status: 'in_progress',
    priority: 'medium',
    category: 'infra',
    assigneeId: 'm5',
    dueDate: days(10),
    tags: ['CI/CD', 'Docker', '최적화'],
    createdAt: past(6),
    updatedAt: past(3),
  },
  {
    id: 't6',
    title: '알림 시스템 구현',
    description: '이메일, 푸시, 인앱 알림 통합 시스템 구현. 사용자별 알림 설정 및 수신 동의 관리 포함.',
    status: 'todo',
    priority: 'medium',
    category: 'feature',
    assigneeId: 'm2',
    dueDate: days(14),
    tags: ['알림', '이메일', '푸시'],
    createdAt: past(3),
    updatedAt: past(3),
  },
  {
    id: 't7',
    title: '모바일 앱 성능 개선',
    description: '앱 초기 로딩 시간 50% 단축 목표. 이미지 지연 로딩, 번들 사이즈 최적화, 캐싱 전략 개선.',
    status: 'review',
    priority: 'high',
    category: 'feature',
    assigneeId: 'm1',
    dueDate: days(5),
    tags: ['모바일', '성능', '최적화'],
    createdAt: past(10),
    updatedAt: past(2),
  },
  {
    id: 't8',
    title: '데이터베이스 마이그레이션',
    description: 'MySQL에서 PostgreSQL로 이전 작업. 데이터 무결성 검증 및 롤백 계획 포함.',
    status: 'todo',
    priority: 'urgent',
    category: 'infra',
    assigneeId: 'm5',
    dueDate: days(2),
    tags: ['DB', 'PostgreSQL', '마이그레이션'],
    createdAt: past(1),
    updatedAt: past(1),
  },
  {
    id: 't9',
    title: '온보딩 가이드 디자인',
    description: '신규 사용자를 위한 인터랙티브 온보딩 플로우 설계. 5단계 투어 및 툴팁 시스템 포함.',
    status: 'done',
    priority: 'medium',
    category: 'design',
    assigneeId: 'm3',
    dueDate: past(5),
    tags: ['온보딩', 'UX', '신규사용자'],
    createdAt: past(20),
    updatedAt: past(5),
  },
  {
    id: 't10',
    title: '검색 기능 고도화',
    description: '엘라스틱서치 도입으로 풀텍스트 검색 및 자동완성 기능 구현. 다국어 형태소 분석 지원.',
    status: 'in_progress',
    priority: 'high',
    category: 'feature',
    assigneeId: 'm2',
    dueDate: days(8),
    tags: ['검색', 'Elasticsearch', '고도화'],
    createdAt: past(7),
    updatedAt: past(4),
  },
  {
    id: 't11',
    title: '팀 권한 관리 기능',
    description: '역할 기반 접근 제어(RBAC) 구현. Admin, Manager, Member 권한 단계 설정 및 UI 포함.',
    status: 'todo',
    priority: 'medium',
    category: 'feature',
    assigneeId: 'm4',
    dueDate: days(21),
    tags: ['RBAC', '권한관리', '보안'],
    createdAt: past(4),
    updatedAt: past(4),
  },
  {
    id: 't12',
    title: '서비스 약관 업데이트',
    description: '개인정보처리방침 및 이용약관 2024년 법령 개정 사항 반영. 법무팀 검토 완료.',
    status: 'done',
    priority: 'low',
    category: 'docs',
    assigneeId: 'm4',
    dueDate: past(10),
    tags: ['법무', '약관', '개인정보'],
    createdAt: past(30),
    updatedAt: past(10),
  },
  {
    id: 't13',
    title: '애널리틱스 대시보드',
    description: '실시간 사용자 행동 분석 대시보드 구현. GA4 연동 및 커스텀 이벤트 트래킹 포함.',
    status: 'review',
    priority: 'medium',
    category: 'feature',
    assigneeId: 'm4',
    dueDate: days(4),
    tags: ['분석', 'GA4', '대시보드'],
    createdAt: past(12),
    updatedAt: past(2),
  },
  {
    id: 't14',
    title: '다국어 지원 추가',
    description: '영어, 일본어 현지화 작업. i18next 도입 및 번역 관리 워크플로우 구축.',
    status: 'todo',
    priority: 'low',
    category: 'feature',
    assigneeId: null,
    dueDate: days(30),
    tags: ['i18n', '다국어', '현지화'],
    createdAt: past(2),
    updatedAt: past(2),
  },
  {
    id: 't15',
    title: '코드 리뷰 프로세스 문서화',
    description: 'PR 리뷰 가이드라인, 코딩 컨벤션, 브랜치 전략 문서 작성. 신규 팀원 온보딩에 활용.',
    status: 'done',
    priority: 'low',
    category: 'docs',
    assigneeId: 'm1',
    dueDate: past(7),
    tags: ['문서화', '코드리뷰', '컨벤션'],
    createdAt: past(25),
    updatedAt: past(7),
  },
];
